name: health_pipeline
version: '1.0.0'
config-version: 2

profile: health_pipeline

model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  health_pipeline:
    staging:
      +materialized: view
    marts:
      +materialized: table
